### ISSUE TITLE
Glass visual error

### ISSUE THREAD

**Issue by purestone9** [Tfarcenim/ColoredBlocks#10]
![image](https://user-images.githubusercontent.com/29181158/75881539-81cb6400-5ddc-11ea-9232-b8dba6c4c218.png)

**Comment by purestone9** [comment]
Minecraft version 1.15.2
Forge version 31.1.14
Mod version 2.0.0

**Comment by Tfarcenim** [comment]
oh no i've been owned by blockrendertype
