### ISSUE TITLE
[Suggestion] to make compatible with Minecraft version 1.12.2

### ISSUE THREAD

**Issue by lightlessfilms** [Tfarcenim/ColoredBlocks#13]
Hi Tfarcenim,

Is it possible to backport this to Minecraft version 1.12.2?
Flat colored blocks has an issue with Architecturecraft because the colors are not rendering correctly.
See issue: https://github.com/TridentMC/ArchitectureCraft/issues/17

The author of Flat Colored Blocks is unfortunately retired

Thank you in advance!

**Comment by Tfarcenim** [comment]
No backports are planned
