### ISSUE TITLE
Cannot run on dedicated server

### ISSUE THREAD

**Issue by SamboyCoding** [Tfarcenim/ColoredBlocks#4]
MC 1.14.3, forge 27.0.60, [this crash](https://hastebin.com/raw/lagakalawi) occurs when you try to run the mod on a dedicated server. 

It's due to [this line](https://github.com/Tfarcenim/ColoredBlocks/blob/master/src/main/java/com/tfar/simplecoloredblocks/SimpleColoredBlocks.java#L175) which apparently causes either ScreenManager or ColorWheelScreen to attempt to be loaded on the server.

**Comment by Tfarcenim** [comment]
fixed in 1.2.0
