### ISSUE TITLE
[1.14.4] On load - [15Aug2019 03:23:49.561] [Client thread/FATAL] [com.tfar.simplecoloredblocks.SimpleColoredBlocks/]: java.lang.NullPointerException

### ISSUE THREAD

**Issue by ProsperCraft** [Tfarcenim/ColoredBlocks#7]
[15Aug2019 03:23:49.561] [Client thread/FATAL] [com.tfar.simplecoloredblocks.SimpleColoredBlocks/]: java.lang.NullPointerException

Trying to diagnose why I can't make a world in single player, and found this line.

[latest.log](https://github.com/Tfarcenim/ColoredBlocks/files/3505057/latest.log)
[debug.log](https://github.com/Tfarcenim/ColoredBlocks/files/3505058/debug.log)

**Comment by ProsperCraft** [comment]
On removing Simplecolored blocks it still locks on single player new world creation, so this was not keeping it from loading.

**Comment by Tfarcenim** [comment]
does this still happen after the hotfix

**Comment by Tfarcenim** [comment]
closed due to inactivity
